// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2N-09V6ebrb0of-J-zc6e-iDCZVCZmss',
    appId: '1:773031169627:web:23cd53335ce2233fe8b97e',
    messagingSenderId: '773031169627',
    projectId: 'biketogether-ids',
    authDomain: 'biketogether-ids.firebaseapp.com',
    databaseURL: 'https://biketogether-ids-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'biketogether-ids.appspot.com',
    measurementId: 'G-MX9ERHEYML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoWH8WaMo5zcA88S1gLCX7vWhdakoVINk',
    appId: '1:773031169627:android:1b0609c415baf405e8b97e',
    messagingSenderId: '773031169627',
    projectId: 'biketogether-ids',
    databaseURL: 'https://biketogether-ids-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'biketogether-ids.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmQLKe2h_x8m1ZdpRWpEgRsXkUdlEiK6U',
    appId: '1:773031169627:ios:3d99b66fae3adfb8e8b97e',
    messagingSenderId: '773031169627',
    projectId: 'biketogether-ids',
    databaseURL: 'https://biketogether-ids-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'biketogether-ids.appspot.com',
    iosClientId: '773031169627-h699pn9vkoei235vo9ki343ikulg2vfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.biketogether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmQLKe2h_x8m1ZdpRWpEgRsXkUdlEiK6U',
    appId: '1:773031169627:ios:8c9d58e0df76fcd8e8b97e',
    messagingSenderId: '773031169627',
    projectId: 'biketogether-ids',
    databaseURL: 'https://biketogether-ids-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'biketogether-ids.appspot.com',
    iosClientId: '773031169627-sf0mnaijtci5305v85v775j4u1qd82s1.apps.googleusercontent.com',
    iosBundleId: 'com.example.biketogether.RunnerTests',
  );
}
