name: Flutter CI

on:
  push:
    branches:
      - master
      - franz
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # setup enviroment
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.6'
          channel: 'stable'
      # check dependencies and run tests
      - run: flutter pub get
      - run: flutter test
      # builds the app
      - run: flutter build apk
      # uploads the apk as an artifact so it can be retrieved next
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
  release:
    needs: build      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        id: download
        with:
          name: release-apk
      - name: Release
        uses: xresloader/upload-to-github-release@v1.3.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "./app-release.apk"
          overwrite: true
          draft: false
          update_latest_release: true